// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trendingService.proto

package com.trendingGrpc;

public interface TrendingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.trendingGrpc.TrendingRequest)
    com.google.protobuf.MessageOrBuilder {
}
