// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trendingService.proto

package com.trendingGrpc;

public interface TrendingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.trendingGrpc.TrendingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string movieId = 1;</code>
   */
  java.util.List<java.lang.String>
      getMovieIdList();
  /**
   * <code>repeated string movieId = 1;</code>
   */
  int getMovieIdCount();
  /**
   * <code>repeated string movieId = 1;</code>
   */
  java.lang.String getMovieId(int index);
  /**
   * <code>repeated string movieId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMovieIdBytes(int index);
}
