// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trendingService.proto

package com.trendingGrpc;

public final class TrendingServiceOuterClass {
  private TrendingServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trendingGrpc_TrendingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trendingGrpc_TrendingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trendingGrpc_TrendingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trendingGrpc_TrendingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025trendingService.proto\022\020com.trendingGrp" +
      "c\"\021\n\017TrendingRequest\"#\n\020TrendingResponse" +
      "\022\017\n\007movieId\030\001 \003(\t2j\n\017TrendingService\022W\n\016" +
      "getTop10Movies\022!.com.trendingGrpc.Trendi" +
      "ngRequest\032\".com.trendingGrpc.TrendingRes" +
      "ponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_trendingGrpc_TrendingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_trendingGrpc_TrendingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trendingGrpc_TrendingRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_trendingGrpc_TrendingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_trendingGrpc_TrendingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trendingGrpc_TrendingResponse_descriptor,
        new java.lang.String[] { "MovieId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
