// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trendingService.proto

package com.trendingGrpc;

/**
 * Protobuf type {@code com.trendingGrpc.TrendingResponse}
 */
public  final class TrendingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.trendingGrpc.TrendingResponse)
    TrendingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrendingResponse.newBuilder() to construct.
  private TrendingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrendingResponse() {
    movieId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrendingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              movieId_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            movieId_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        movieId_ = movieId_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trendingGrpc.TrendingServiceOuterClass.internal_static_com_trendingGrpc_TrendingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trendingGrpc.TrendingServiceOuterClass.internal_static_com_trendingGrpc_TrendingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trendingGrpc.TrendingResponse.class, com.trendingGrpc.TrendingResponse.Builder.class);
  }

  public static final int MOVIEID_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList movieId_;
  /**
   * <code>repeated string movieId = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getMovieIdList() {
    return movieId_;
  }
  /**
   * <code>repeated string movieId = 1;</code>
   */
  public int getMovieIdCount() {
    return movieId_.size();
  }
  /**
   * <code>repeated string movieId = 1;</code>
   */
  public java.lang.String getMovieId(int index) {
    return movieId_.get(index);
  }
  /**
   * <code>repeated string movieId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMovieIdBytes(int index) {
    return movieId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < movieId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, movieId_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < movieId_.size(); i++) {
        dataSize += computeStringSizeNoTag(movieId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMovieIdList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trendingGrpc.TrendingResponse)) {
      return super.equals(obj);
    }
    com.trendingGrpc.TrendingResponse other = (com.trendingGrpc.TrendingResponse) obj;

    boolean result = true;
    result = result && getMovieIdList()
        .equals(other.getMovieIdList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMovieIdCount() > 0) {
      hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
      hash = (53 * hash) + getMovieIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trendingGrpc.TrendingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trendingGrpc.TrendingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trendingGrpc.TrendingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trendingGrpc.TrendingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trendingGrpc.TrendingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trendingGrpc.TrendingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trendingGrpc.TrendingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trendingGrpc.TrendingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trendingGrpc.TrendingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.trendingGrpc.TrendingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trendingGrpc.TrendingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trendingGrpc.TrendingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trendingGrpc.TrendingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.trendingGrpc.TrendingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.trendingGrpc.TrendingResponse)
      com.trendingGrpc.TrendingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trendingGrpc.TrendingServiceOuterClass.internal_static_com_trendingGrpc_TrendingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trendingGrpc.TrendingServiceOuterClass.internal_static_com_trendingGrpc_TrendingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trendingGrpc.TrendingResponse.class, com.trendingGrpc.TrendingResponse.Builder.class);
    }

    // Construct using com.trendingGrpc.TrendingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      movieId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trendingGrpc.TrendingServiceOuterClass.internal_static_com_trendingGrpc_TrendingResponse_descriptor;
    }

    @java.lang.Override
    public com.trendingGrpc.TrendingResponse getDefaultInstanceForType() {
      return com.trendingGrpc.TrendingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.trendingGrpc.TrendingResponse build() {
      com.trendingGrpc.TrendingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trendingGrpc.TrendingResponse buildPartial() {
      com.trendingGrpc.TrendingResponse result = new com.trendingGrpc.TrendingResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        movieId_ = movieId_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.movieId_ = movieId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trendingGrpc.TrendingResponse) {
        return mergeFrom((com.trendingGrpc.TrendingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trendingGrpc.TrendingResponse other) {
      if (other == com.trendingGrpc.TrendingResponse.getDefaultInstance()) return this;
      if (!other.movieId_.isEmpty()) {
        if (movieId_.isEmpty()) {
          movieId_ = other.movieId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMovieIdIsMutable();
          movieId_.addAll(other.movieId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.trendingGrpc.TrendingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.trendingGrpc.TrendingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList movieId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMovieIdIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        movieId_ = new com.google.protobuf.LazyStringArrayList(movieId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string movieId = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMovieIdList() {
      return movieId_.getUnmodifiableView();
    }
    /**
     * <code>repeated string movieId = 1;</code>
     */
    public int getMovieIdCount() {
      return movieId_.size();
    }
    /**
     * <code>repeated string movieId = 1;</code>
     */
    public java.lang.String getMovieId(int index) {
      return movieId_.get(index);
    }
    /**
     * <code>repeated string movieId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMovieIdBytes(int index) {
      return movieId_.getByteString(index);
    }
    /**
     * <code>repeated string movieId = 1;</code>
     */
    public Builder setMovieId(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMovieIdIsMutable();
      movieId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string movieId = 1;</code>
     */
    public Builder addMovieId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMovieIdIsMutable();
      movieId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string movieId = 1;</code>
     */
    public Builder addAllMovieId(
        java.lang.Iterable<java.lang.String> values) {
      ensureMovieIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, movieId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string movieId = 1;</code>
     */
    public Builder clearMovieId() {
      movieId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string movieId = 1;</code>
     */
    public Builder addMovieIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMovieIdIsMutable();
      movieId_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.trendingGrpc.TrendingResponse)
  }

  // @@protoc_insertion_point(class_scope:com.trendingGrpc.TrendingResponse)
  private static final com.trendingGrpc.TrendingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trendingGrpc.TrendingResponse();
  }

  public static com.trendingGrpc.TrendingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrendingResponse>
      PARSER = new com.google.protobuf.AbstractParser<TrendingResponse>() {
    @java.lang.Override
    public TrendingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrendingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrendingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrendingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trendingGrpc.TrendingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

